import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Presence from "@/components/Presence";

const helvetica = localFont({
  src: "./fonts/HelveticaNeueLight.ttf",
  variable: "--font-helvetica-neue",
  // weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${helvetica.className} text-primary`}
      >
        <Presence>
          {children}
        </Presence>
      </body>
    </html>
  );
}
